// import "./styles/global.css";
// import type { Metadata } from "next";
// import { Poppins, Josefin_Sans } from "next/font/google";
// import { ThemeProvider } from "./utils/theme-provider";
// import { SessionProvider } from "next-auth/react";
// import { Providers } from "./provider";
// import { useLoadUserQuery } from "@/redux/features/api/apiSlice";
// // import { useEffect } from "react";
// import Loader from "./components/Loader/Loader";
// import socketIO from "socket.io-client";
// import { useEffect } from "react";
// const ENDPOINT  = process.env.NEXT_PUBLIC_SOCKET_SERVER_URL || "";
// const socketId = socketIO(ENDPOINT, {
//   transports: ["websocket"],
// })

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-Poppins",
// });

// const josefin = Josefin_Sans({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-Josefin",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${poppins.variable} ${josefin.variable}
//           bg-white
//           bg-no-repeat
//           dark:bg-linear-to-b
//           dark:from-gray-900
//           dark:to-black
//           duration-300
//         `}
//       >
//         <Providers>
//         <SessionProvider>
//        <ThemeProvider attribute='class' defaultTheme="system" enableSystem>
//         <Custom>{children}</Custom>
//         <Toaster position="top-center" reverseOrder={false}/>
//         </ThemeProvider>
//         </SessionProvider>
//        </Providers>
//       </body>
//     </html>
//   );
// }

// const Custom: React.FC<{children: React.ReactNode}> = ({children}) => {
//   const {isLoading} = useLoadUserQuery({});

//   useEffect(() => {
//     socketId.on("connection", () => {});
//   },[])

//   return (
//     <>
//     {
//       isLoading ? <Loader/> : <>{children} </>
//     }
//     </>
//   )
// }


// 'use client'
// import "./styles/global.css";
// import {Poppins} from "next/font/google"
// import {Josefin_Sans} from "next/font/google"
// import { ThemeProvider } from "./utils/theme-provider";
// import {Toaster} from "react-hot-toast"
// import { Providers } from "./provider";
// import { SessionProvider } from "next-auth/react";
// import { useLoadUserQuery } from "@/redux/features/api/apiSlice";
// import Loader from "./components/Loader/Loader"
// import socketIO from "socket.io-client";
// import { useEffect } from "react";
// const ENDPOINT  = process.env.NEXT_PUBLIC_SOCKET_SERVER_URL || "";
// const socketId = socketIO(ENDPOINT, {
//   transports: ["websocket"],
// })


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         // className={`${poppins.variable} ${josefin.variable} !bg-white bg-no-repeat dark:bg-gradient-to-b dark:from-gray-900 dark:to-black duration-300`}
//         >
//        <Providers>
//         <SessionProvider>
//        <ThemeProvider attribute='class' defaultTheme="system" enableSystem>
//         <Custom>{children}</Custom>
//         <Toaster position="top-center" reverseOrder={false}/>
//         </ThemeProvider>
//         </SessionProvider>
//        </Providers>
//       </body>
//     </html>
//   );
// }

// const Custom: React.FC<{children: React.ReactNode}> = ({children}) => {
//   const {isLoading} = useLoadUserQuery({});

//   useEffect(() => {
//     socketId.on("connection", () => {});
//   },[])

//   return (
//     <>
//     {
//       isLoading ? <Loader/> : <>{children} </>
//     }
//     </>
//   )
// }

// app/layout.tsx
// app/layout.tsx
// app/layout.tsx
import "./styles/global.css";
import { Providers } from "./provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}





